### ISSUE TITLE
Feature Request: Ability to assign a Team to a Service

### ISSUE THREAD

**Issue by davidarmstronglewis** [PagerDuty/terraform-provider-pagerduty#109]
According to the docs (https://v2.developer.pagerduty.com/v2/page/api-reference#!/Services/put_services_id) it's possible to assign Teams directly to a Service. This isn't possible with the Terraform PagerDuty Provider but should be possible and valuable.

**Comment by etienne-napoleone** [comment]
Is it possible to implement that? That value is quite present/highlighted in the UI and best practices says:
> Start by considering who is responsible for the service you are setting up. A service should be wholly owned by the team on-call for it. 

_https://community.pagerduty.com/t/service-configuration-guide/5110_

**Comment by stefansedich** [comment]
Would like to be able to do this too, anoying as going to the services page I don't see any services until I clear all filters.

**Comment by bassrock** [comment]
FYI according to the comments in #187 you dont't actually add teams to a service with PagerDuty. Instead, you associate teams to an Escalation Policy, then an Escalation Policy to a Service. When doing it that way, PagerDuty's interface behaves as expected.

**Comment by wlonkly** [comment]
> it's possible to assign Teams directly to a Service

After I saw @bassrock's PR and his comments there, I did some digging into this, and it looks like you can `GET` a service's teams through the REST API, but you can't set them. Inside PagerDuty, that's because teams are an attribute of an escalation policy, and EPs are an attribute of a service (so a service has an EP which has a team).

So I think that means you can do this now, just not directly:

```terraform
resource "pagerduty_team" "engineering" {
  name        = "Engineering"
  description = "All engineering"
}

resource "pagerduty_escalation_policy" "engineering" {
  name  = "Engineering Escalation Policy"
  teams = [pagerduty_team.engineering.id]
  [...]
}
  
resource "pagerduty_service" "service" {
  name              = "My Web App"
  escalation_policy = pagerduty_escalation_policy.engineering.id
  [...]
}
```
and then the "My Web App" service will be owned by the "Engineering" team, via the Engineering EP.

**Comment by wlonkly** [comment]
Woops, @bassrock beat me to it, but I'll leave my comment here too :)

**Comment by stmcallister** [comment]
Looks like this resolved? If I'm mistaken please reopen or post a new issue.
