### ISSUE TITLE
pagerduty_priority not found in provider.pagerduty v1.7.1

### ISSUE THREAD

**Issue by mhyzon** [PagerDuty/terraform-provider-pagerduty#229]
I hope I'm not missing something stupid

### Terraform Version
```
$ terraform -v
Terraform v0.12.23
+ provider.pagerduty v1.7.1
```
(I realize terraform is at 0.12.25, but this looks to be a provider issue)

### Affected Resource(s)
- pagerduty_priority

### Terraform Configuration Files
```hcl
resource "pagerduty_priority" "P0" {
  name = "P0"
}
```

### Debug Output
```
$ terraform plan 
Acquiring state lock. This may take a few moments...

Error: Invalid resource type

  on priorities.tf line 1, in resource "pagerduty_priority" "P0":
   1: resource "pagerduty_priority" "P0" {

The provider provider.pagerduty does not support resource type
"pagerduty_priority".
```

### Expected Behavior
terraform should plan/apply/import `pagerduty_priority` resources

The [CHANGELOG](https://github.com/terraform-providers/terraform-provider-pagerduty/commit/dbb225b83987f29e888554e7785c6783c65b3ef1#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) indicates the feature should be there.

### Actual Behavior
terraform reports provider does not support resource type "pagerduty_priority"

### Steps to Reproduce
`terraform apply` with a configuration including a `resource "pagerduty_priority" "foo" {}`  

or 

`terraform import -allow-missing-config pagerduty_priority.foo PXYZ123`

### References
- #219

**Comment by mhyzon** [comment]
PS, docs on the website **DO NOT** mention this new resource type, FWIW.

**Comment by stmcallister** [comment]
Hello! sorry for the confusion. It's actually a data source object and not a resource, since you can't add or modify priorities through the PagerDuty API. 

However, I failed to get the doc added to the side navigation. That fix has been merged to master, but a new version of the provider hasn't been published yet.  Until then, you can find the doc here:  https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/website/docs/d/priority.html.markdown

**Comment by mhyzon** [comment]
Ok, thanks!
